
require './backtracking.rb'
require './levenshtein.rb'
require './rabin_karp.rb'
require './boyer_moore.rb'
require './graphs.rb'
require './graph_traversal.rb'
require './dijkstra.rb'
require './map_reduce.rb'
require './page_rank.rb'
require './dynamic_programming.rb'
require './automata.rb'
require './priority_queue.rb'
require './grids.rb'
require './astar_search.rb'