
require './algorithms/backtracking.rb'
require './algorithms/levenshtein.rb'
require './algorithms/rabin_karp.rb'
require './algorithms/boyer_moore.rb'
require './algorithms/graphs.rb'
require './algorithms/graph_traversal.rb'
require './algorithms/dijkstra.rb'
require './algorithms/map_reduce.rb'
require './algorithms/page_rank.rb'
require './algorithms/dynamic_programming.rb'
require './algorithms/automata.rb'
require './algorithms/priority_queue.rb'
require './algorithms/grids.rb'
require './algorithms/astar_search.rb'
require './algorithms/karmarkar_karp.rb'