
require './backtracking.rb'
require './levenshtein.rb'
require './rabin_karp.rb'
require './graphs.rb'
require './dijkstra.rb'
require './map_reduce.rb'
require './page_rank.rb'
require './dynamic_programming.rb'
require './automata.rb'